### ISSUE TITLE
Crashed when playing video

### ISSUE THREAD

**Issue by ghost** [Docile-Alligator/Infinity-For-Reddit#1396]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0

### Where did you get the app from

F-Droid

### Android version

13

### Device model

Oneplus 11

### First occurred

3 weeks ago

### Expected behaviour

When i open/play any video, the app crashes. 

### Logs

```
`` Stacktrace ``

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:536)
	at java.nio.ByteBufferAsFloatBuffer.put(ByteBufferAsFloatBuffer.java:109)
	at com.otaliastudios.opengl.draw.GlRect.setRect(GlRect.kt:64)
	at com.otaliastudios.opengl.draw.GlRect.setRect(GlRect.kt:47)
	at com.otaliastudios.zoom.ZoomSurfaceView.onContentOrContainerSizeChanged(ZoomSurfaceView.kt:238)
	at com.otaliastudios.zoom.ZoomSurfaceView.onMeasure(ZoomSurfaceView.kt:215)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:26690)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1792)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:627)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:827)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2753)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3084)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2458)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1393)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1401)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1038)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:437)
	at android.view.Choreographer.doFrame(Choreographer.java:909)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1376)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8379)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 73
Thread time: 0 hr 0 min, 6 sec

`` END of thread info ``

`` Device info ``

Report ID: f9e60a09-6628-4cce-a1fb-4f8997b6f31b
Device ID: 87578f192d82c6de
Application version: 114
Default launcher: com.android.launcher
Timezone name: Eastern Standard Time
Timezone ID: America/New_York
Version release: 13
Version incremental : T.R4T3.ded3a6-6ce9-6cea
Version SDK: 33
Board: kalama
Bootloader: unknown
Brand: OnePlus
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OP594DL1
Display: CPH2451_11_A.07
Fingerprint: OnePlus/CPH2451/OP594DL1:13/TP1A.220905.001/T.R4T3.ded3a6-6ce9-6cea:user/release-keys
Hardware: qcom
Host: dg02-pool03-kvm203
ID: TP1A.220905.001
Manufacturer: OnePlus
Product: CPH2451
Build time: 1675265110000
Build time formatted: 01-02-2023 10:25:10
Type: user
Radio: Q_V1_P14,Q_V1_P14
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 61
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 8
Up time with sleep: 6 hr 8 min, 21 sec
Up time without sleep: 5 hr 40 min, 50 sec

`` END of Device info ``

`` Exit reasons ``


`` Exit reason #1 ``
Description: remove task|J:905
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 02-03-2023 02:12:57
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: remove task|J:905
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 02-03-2023 01:55:10
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: remove task|J:905
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 01-03-2023 22:50:55
`` END of exit reason #3 ``


`` END of exit reasons ``

`` Application info ``

App name: Infinity
Version code: 114
Version name: 5.4.0
Package name: ml.docilealligator.infinityforreddit
Short package name: infinityforreddit
Flavor: N/A
Signatures: QlQdffRkEvngb60pfoOWQCnQSII=
Is debuggable: No
First installed: 01-03-2023 20:24:05
Last updated: 01-03-2023 20:24:05
Requested permissions: android.permission.ACCESS_NETWORK_STATE, android.permission.INTERNET, android.permission.SET_WALLPAPER, android.permission.SET_WALLPAPER_HINTS, android.permission.FOREGROUND_SERVICE, android.permission.WAKE_LOCK, android.permission.POST_NOTIFICATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.RECEIVE_BOOT_COMPLETED, ml.docilealligator.infinityforreddit.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: default_post_layout = 0, mute_autoplaying_videos = true, swipe_up_to_hide_jump_to_next_top_level_comm
```

**Comment by xbec65** [comment]
Crashed today. Here's the crash report as well. 

```
`` Stacktrace ``

java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:536)
	at java.nio.ByteBufferAsFloatBuffer.put(ByteBufferAsFloatBuffer.java:109)
	at com.otaliastudios.opengl.draw.GlRect.setRect(GlRect.kt:63)
	at com.otaliastudios.opengl.draw.GlRect.setRect(GlRect.kt:47)
	at com.otaliastudios.zoom.ZoomSurfaceView.onContentOrContainerSizeChanged(ZoomSurfaceView.kt:238)
	at com.otaliastudios.zoom.ZoomSurfaceView.onMeasure(ZoomSurfaceView.kt:215)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:26690)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1792)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:627)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:827)
	at android.view.View.measure(View.java:26690)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4095)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2753)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3084)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2458)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1393)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1401)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1038)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:437)
	at android.view.Choreographer.doFrame(Choreographer.java:909)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1376)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8379)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 84
Thread time: 0 hr 1 min, 4 sec

`` END of thread info ``

`` Device info ``

Report ID: 38687b11-fc77-48bc-9b25-b735580b093f
Device ID: 87578f192d82c6de
Application version: 114
Default launcher: com.android.launcher
Timezone name: Eastern Standard Time
Timezone ID: America/New_York
Version release: 13
Version incremental : T.R4T3.ded3a6-6ce9-6cea
Version SDK: 33
Board: kalama
Bootloader: unknown
Brand: OnePlus
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OP594DL1
Display: CPH2451_11_A.07
Fingerprint: OnePlus/CPH2451/OP594DL1:13/TP1A.220905.001/T.R4T3.ded3a6-6ce9-6cea:user/release-keys
Hardware: qcom
Host: dg02-pool03-kvm203
ID: TP1A.220905.001
Manufacturer: OnePlus
Product: CPH2451
Build time: 1675265110000
Build time formatted: 01-02-2023 10:25:10
Type: user
Radio: Q_V1_P14,Q_V1_P14
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 17
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 8
Up time with sleep: 40 hr 38 min, 50 sec
Up time without sleep: 22 hr 24 min, 10 sec

`` END of Device info ``

`` Exit reasons ``


`` Exit reason #1 ``
Description: remove task|J:905
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 03-03-2023 03:59:22
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: remove task|J:900
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 03-03-2023 01:59:31
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: remove task|J:905
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 03-03-2023 01:56:36
`` END of exit reason #3 ``


`` END of exit reasons ``

`` Application info ``

App name: Infinity
Version code: 114
Version name: 5.4.0
Package name: ml.docilealligator.infinityforreddit
Short package name: infinityforreddit
Flavor: N/A
Signatures: QlQdffRkEvngb60pfoOWQCnQSII=
Is debuggable: No
First installed: 01-03-2023 20:24:05
Last updated: 01-03-2023 20:24:05
Requested permissions: android.permission.ACCESS_NETWORK_STATE, android.permission.INTERNET, android.permission.SET_WALLPAPER, android.permission.SET_WALLPAPER_HINTS, android.permission.FOREGROUND_SERVICE, android.permission.WAKE_LOCK, android.permission.POST_NOTIFICATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.RECEIVE_BOOT_COMPLETED, ml.docilealligator.infinityforreddit.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: default_post_layout = 0, mute_autoplaying_videos = false, swipe_up_to_hide_jump_to_next_top_level
```

**Comment by Docile-Alligator** [comment]
This is related to the zoom functionality in ViewVideoActivity.

**Comment by Docile-Alligator** [comment]
https://github.com/natario1/ZoomLayout/issues/225

**Comment by Docile-Alligator** [comment]
The next version will disable rendering ZoomSurfaceView and you have to disable pinch to zoom video in order to avoid the crash.
