### ISSUE TITLE
Certain multireddits in Main Page crash after open the app

### ISSUE THREAD

**Issue by JJWilson-75** [Docile-Alligator/Infinity-For-Reddit#1656]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.2.3

### Where did you get the app from

Other

### Android version

12

### Device model

RMX3690

### First occurred

Today after installing new version 

### Steps to reproduce

1. Go to Customize Tabs in Main Page
2. Select 2 for Tab Count (Home and All)
3. Enable Show Favourite Multireddits (preferably at least 4 multireddits)
4. Exit the app and open it again 
5. Go straight to any multireddits between the third and second to last appearing in the Main Page (the first two multireddits and the last one are unaffected by this regardless of the number of favourite multireddits)
6. The app crash unless you select other tabs like All, the first two multireddits, or the last multireddit on the Main Page, then you go to the fault-causing multireddits

### Expected behaviour

After open the app, I should able to browse any multireddits in the Main Page

### Current behaviour

I have to select one of the All tab, the first two multireddits or the last one before going to any multireddits between the third and second to last to prevent it from crashing

### Logs

`` Stacktrace ``

java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore(Unknown Source:35)
	at androidx.lifecycle.u0.<init>(Unknown Source:10)
	at ml.docilealligator.infinityforreddit.fragments.PostFragment.r0(Unknown Source:210)
	at ml.docilealligator.infinityforreddit.fragments.PostFragment.D0(Unknown Source:75)
	at ml.docilealligator.infinityforreddit.fragments.PostFragment.t(Unknown Source:0)
	at id.t0.a(Unknown Source:2)
	at pc.c1.t(Unknown Source:0)
	at pc.c1.d(Unknown Source:0)
	at pc.b1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7971)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1017)

`` END of stacktrace ``

**Comment by Docile-Alligator** [comment]
I will look into it.

**Comment by martixy** [comment]
All my multireddits are missing for me on v7.2.3, tho I have not observed any crashes yet.

**Comment by Docile-Alligator** [comment]
@martixy Cannot reproduce this. Where did you create the multireddits?
