### ISSUE TITLE
Crashing when trying to open some posts.

### ISSUE THREAD

**Issue by knoxy5467** [Docile-Alligator/Infinity-For-Reddit#1683]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.2.8

### Where did you get the app from

Other

### Android version

14

### Device model

Pixel 8a

### First occurred

Yesterday 

### Steps to reproduce

Simply browsing, I do not have a common trend.

Recently installed on new phone.

### Expected behaviour

Open the post I clicked on.

### Current behaviour

Crashes to home screen closes and loses scroll progress 

### Logs

```
`` Stacktrace ``

java.lang.RuntimeException: Unable to start activity ComponentInfo{ml.docilealligator.infinityforreddit/ml.docilealligator.infinityforreddit.activities.ViewVideoActivity}: android.view.InflateException: Binary XML file line #30 in ml.docilealligator.infinityforreddit:layout/activity_view_video: Binary XML file line #30 in ml.docilealligator.infinityforreddit:layout/activity_view_video: Error inflating class androidx.media3.ui.PlayerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3993)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.view.InflateException: Binary XML file line #30 in ml.docilealligator.infinityforreddit:layout/activity_view_video: Binary XML file line #30 in ml.docilealligator.infinityforreddit:layout/activity_view_video: Error inflating class androidx.media3.ui.PlayerView
Caused by: android.view.InflateException: Binary XML file line #30 in ml.docilealligator.infinityforreddit:layout/activity_view_video: Error inflating class androidx.media3.ui.PlayerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:742)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:894)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:849)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1011)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1014)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1014)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:570)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
	at ml.docilealligator.infinityforreddit.databinding.ActivityViewVideoBinding.inflate(ActivityViewVideoBinding.java:63)
	at ml.docilealligator.infinityforreddit.databinding.ActivityViewVideoBinding.inflate(ActivityViewVideoBinding.java:57)
	at ml.docilealligator.infinityforreddit.activities.ViewVideoActivity.onCreate(ViewVideoActivity.java:278)
	at android.app.Activity.performCreate(Activity.java:8960)
	at android.app.Activity.performCreate(Activity.java:8938)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ClassCastException: com.google.android.material.button.MaterialButton cannot be cast to android.widget.ImageView
	at androidx.media3.ui.PlayerControlView.<init>(PlayerControlView.java:666)
	at androidx.media3.ui.PlayerView.<init>(PlayerView.java:568)
	at androidx.media3.ui.PlayerView.<init>(PlayerView.java:340)
	... 33 more


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 84
Thread time: 0 hr 0 min, 28 sec

`` END of thread info ``

`` Device info ``

Report ID: c8fcfd39-3422-4816-a78d-7a5f0b75046a
Device ID: eadb83ed77268c4e
Application version: 175
Default launcher: com.android.settings
Timezone name: Eastern Standard Time
Timezone ID: America/New_York
Version release: 14
Version incremental : 11860263
Version SDK: 34
Board: akita
Bootloader: akita-14.5-11693900
Brand: google
CPU ABIS 32: N/A
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a
Device: akita
Display: AP2A.240605.024
Fingerprint: google/akita/akita:14/AP2A.240605.024/11860263:user/release-keys
Hardware: akita
Host: r-82b05a39f2cf359a-t9k0
ID: AP2A.240605.024
Manufacturer: Google
Product: akita
Build time: 1716016199000
Build time formatted: 18-05-2024 03:09:59
Type: user
Radio: g5300o-240308-240517-B-11857457,g5300o-240308-240517-B-11857457
Tags: release-keys
User: android-build
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 62
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 9
Up time with sleep: 4 hr 37 min, 1 sec
Up time without sleep: 1 hr 29 min, 1 sec

`` END of Device info ``

`` Exit reasons ``


`` Exit reason #1 ``
Description: ISOLATED NOT NEEDED isolated not needed
Importance: SERVICE
Reason: OTHER
Timestamp: 02-07-2024 19:21:19
`` END of exit reason #1 ``


`` END of exit reasons ``

`` Application info ``

App name: Infinity
Version code: 175
Version name: 7.2.8
Package name: ml.docilealligator.infinityforreddit
Short package name: infinityforreddit
Flavor: N/A
Signatur
```

**Comment by Docile-Alligator** [comment]
Please compile Infinity again. Make sure you use the commit with the latest release tag.
