### ISSUE TITLE
Infinity crashing when posting, cross posting, downloading images and videos

### ISSUE THREAD

**Issue by Lachlan-R-Williams** [Docile-Alligator/Infinity-For-Reddit#1701]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.3.1

### Where did you get the app from

Google Play

### Android version

9

### Device model

samsung SM-T380

### First occurred

1

### Steps to reproduce

1: Make a post of any type.
2: Trying to crosspost.
3: Attempting to download any image or video.

### Expected behaviour

Function normally.

### Current behaviour

When making a post on Reddit through Inifinty of any type, crossposting or downloading an image or video, the operation will fail as the app crashes.

### Logs

```
`` Stacktrace ``

java.lang.IllegalArgumentException: You're trying to build a job with no constraints, this is not allowed.
	at android.app.job.JobInfo$Builder.build(JobInfo.java:1532)
	at ml.docilealligator.infinityforreddit.services.DownloadMediaService.f(SourceFile:1)
	at ml.docilealligator.infinityforreddit.activities.ViewImageOrGifActivity.o1(SourceFile:1)
	at ml.docilealligator.infinityforreddit.activities.ViewImageOrGifActivity.v1(SourceFile:1)
	at ml.docilealligator.infinityforreddit.activities.ViewImageOrGifActivity.onOptionsItemSelected(Unknown Source:27)
	at android.app.Activity.onMenuItemSelected(Activity.java:3644)
	at d.j.onMenuItemSelected(SourceFile:6)
	at s0.k.onMenuItemSelected(SourceFile:1)
	at i.c.onMenuItemSelected(SourceFile:1)
	at n.i.onMenuItemSelected(SourceFile:3)
	at i.h.a(SourceFile:23)
	at androidx.appcompat.view.menu.e.h(SourceFile:1)
	at androidx.appcompat.view.menu.g.k(SourceFile:1)
	at androidx.appcompat.view.menu.e.P(SourceFile:1)
	at androidx.appcompat.view.menu.e.O(SourceFile:1)
	at androidx.appcompat.widget.ActionMenuView.a(SourceFile:1)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7357)
	at android.widget.TextView.performClick(TextView.java:14263)
	at android.view.View.performClickInternal(View.java:7323)
	at android.view.View.access$3200(View.java:849)
	at android.view.View$PerformClick.run(View.java:27884)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 38
Thread time: 0 hr 0 min, 9 sec

`` END of thread info ``

`` Device info ``

Report ID: 3a6072c5-bff8-4ecc-99d5-fd14f95d9ea1
Device ID: 4b67351e274f2977
Application version: 180
Default launcher: com.sec.android.app.launcher
Timezone name: Australian Eastern Standard Time
Timezone ID: Australia/Sydney
Version release: 9
Version incremental : T380DXS4CUD3
Version SDK: 28
Board: msm8937
Bootloader: T380DXS4CUD3
Brand: samsung
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: N/A
Supported ABIS: armeabi-v7a, armeabi
Device: gta2swifi
Display: PPR1.180610.011.T380DXS4CUD3
Fingerprint: samsung/gta2swifidx/gta2swifi:9/PPR1.180610.011/T380DXS4CUD3:user/release-keys
Hardware: qcom
Host: SWDH7021
ID: PPR1.180610.011
Manufacturer: samsung
Product: gta2swifidx
Build time: 1619693337000
Build time formatted: 29-04-2021 20:48:57
Type: user
Radio: null
Tags: release-keys
User: dpi
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: N/A
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 84
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc APQ8017
Revision	: 0005
Serial		: 3469493634
Processor	: ARMv7 Processor rev 4 (v7l)
Number of CPU cores: 4
Up time with sleep: 13 hr 58 min, 4 sec
Up time without sleep: 5 hr 17 min, 15 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Infinity
Version code: 180
Version name: 7.3.1
Package name: ml.docilealligator.infinityforreddit
Short package name: infinityforreddit
Flavor: N/A
Signatures: XFN80TR5rgSMbsH+WZ5oyxarmIU=
Is debuggable: No
First installed: 22-08-2024 03:31:41
Last updated: 22-08-2024 03:31:41
Requested permissions: android.permission.ACCESS_NETWORK_STATE, android.permission.INTERNET, android.permission.SET_WALLPAPER, android.permission.SET_WALLPAPER_HINTS, android.permission.FOREGROUND_SERVICE, android.permission.WRITE_EXTERNAL_STORAGE, android.permission.WAKE_LOCK, android.permission.POST_NOTIFICATIONS, android.permission.RUN_USER_INITIATED_JOBS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, com.android.vending.BILLING, android.permission.RECEIVE_BOOT_COMPLETED, ml.docilealligator.infinityforreddit.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION, android.permission.READ_EXTERNAL_STORAGE
Default prefs: separate_folder_for_each_subreddit = true, save_nsfw_media_in_different_folder = false, gif_download_location = content://com.android.externalstorage.documents/tree/C4B2-1BEE%3APictures, lazy_mode_interval = 2.5, amoled_dark = false, theme = 1, video_download_location = content://com.android.externalstorage.documents/tree/C4B2-1BEE%3AVideos, enable_material_you = false, image_download_location = content://com.android.externalstorage.documents/tree/C4B2-1BEE%3APictures
Default prefs: separate_folder_for_each_subreddit = true, save_nsfw_media_in_different_folder = false, gif_download_location = content://com.android.externalstorage.documents/tree/C4B2-1BEE%3APictures, lazy_mode_interval = 2.5, amoled_dark = false, theme = 1, video_download_location = content://com.android.externalstorage.documents/tree/C4B2-1BEE%3AVideos, enable_material_you = false, image_download_location = content://com.android.externalstorage.documents/tree/C4B2-1BEE%3APictures

`` END of Application info ``


`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``
```

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/5d1466b5498eb2be7ff8c0ad5983e2833ad15115

Please download v7.3.2 after Google Play finishes reviewing the update.
