### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Kiivii21** [Docile-Alligator/Infinity-For-Reddit#1710]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.3.0

### Where did you get the app from

Other

### Android version

14

### Device model

samsung SM-G991B

### First occurred

2 weeks ago

### Steps to reproduce

When I switch to custom feeds, it crashes

### Logs

```
`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at ml.docilealligator.infinityforreddit.post.PostPagingSource.<init>(PostPagingSource.java:121)
	at ml.docilealligator.infinityforreddit.post.PostViewModel.returnPagingSoruce(PostViewModel.java:288)
	at ml.docilealligator.infinityforreddit.post.PostViewModel$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
	at androidx.paging.Pager$flow$2.invokeSuspend(Pager.kt:93)
	at androidx.paging.Pager$flow$2.invoke(Unknown Source:8)
	at androidx.paging.Pager$flow$2.invoke(Unknown Source:2)
	at androidx.paging.PageFetcher.generateNewPagingSource(PageFetcher.kt:210)
	at androidx.paging.PageFetcher.access$generateNewPagingSource(PageFetcher.kt:32)
	at androidx.paging.PageFetcher$flow$1$2.invokeSuspend(PageFetcher.kt:73)
	at androidx.paging.PageFetcher$flow$1$2.invoke(Unknown Source:15)
	at androidx.paging.PageFetcher$flow$1$2.invoke(Unknown Source:10)
	at androidx.paging.FlowExtKt$simpleScan$1$1.emit(FlowExt.kt:56)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
	at androidx.paging.PageFetcher$flow$1$1.invokeSuspend(PageFetcher.kt:63)
	at androidx.paging.PageFetcher$flow$1$1.invoke(Unknown Source:8)
	at androidx.paging.PageFetcher$flow$1$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.FlowKt__EmittersKt$onStart$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:117)
	at androidx.paging.FlowExtKt$simpleScan$1.invokeSuspend(FlowExt.kt:55)
	at androidx.paging.FlowExtKt$simpleScan$1.invoke(Unknown Source:8)
	at androidx.paging.FlowExtKt$simpleScan$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$filterNotNull$$inlined$unsafeTransform$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:27)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:25)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at androidx.lifecycle.BlockRunner.maybeRun(CoroutineLiveData.kt:175)
	at androidx.lifecycle.CoroutineLiveData.onActive(CoroutineLiveData.kt:241)
	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:405)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:481)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
	at androidx.lifecycle.LiveData.observe(LiveData.java:205)
	at ml.docilealligator.infinityforreddit.fragments.PostFragment.bindPostViewModel(PostFragment.java:1241)
	at ml.docilealligator.infinityforreddit.fragments.PostFragment.initializeAndBindPostViewModel(PostFragment.java:1211)
	at ml.docilealligator.infinityforreddit.fragments.PostFragment.lambda$onCreateView$2$ml-docilealligator-infinityforreddit-fragments-PostFragment(PostFragment.java:920)
	at ml.docilealligator.infinityforreddit.fragments.PostFragment$$ExternalSyntheticLambda16.success(D8$$SyntheticClass:0)
	at ml.docilealligator.infinityforreddit.FetchPostFilterReadPostsAndConcatenatedSubredditNames.lambda$fetchPostFilterAndReadPosts$1(FetchPostFilterReadPostsAndConcatenatedSubredditNames.java:40)
	at ml.docilealligator.infinityforreddit.FetchPostFilterReadPostsAndConcatenatedSubredditNames$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e988a1, Dispatchers.Main.immediate]


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 60
Thread time: 0 hr 0 min, 7 sec

`` END of thread info ``

`` Device info ``

Report ID: db25edc0-440e-4c6c-9e5e-fff12c1a186c
Device ID: faa76bac316f8f89
Application version: 179
Default launcher: com.sec.android.app.launcher
Timezone name: GMT+03:00
Timezone ID: Europe/Istanbul
Version release: 14
Version incremental : G991BXXUCGXGC
Version SDK: 34
Board: exynos2100
Bootloader: G991BXXUCGXGC
Brand: samsung
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, 
```

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/478b2db4e583ff4577e421f1f115ef8d4d7626ef

Please build the app again.
