### ISSUE TITLE
Unable to add account 

### ISSUE THREAD

**Issue by Honkertonken** [Docile-Alligator/Infinity-For-Reddit#1723]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.3.4

### Where did you get the app from

Other

### Android version

14

### First occurred

Today

### Steps to reproduce

1. Click on "add an account"
Crash

### Expected behaviour

Show login page.

### Current behaviour

Add an account does not load any page or instructions at all, instead the app just instantly crashes.

### Logs

```
`` Stacktrace ``

java.lang.NoSuchMethodError: No static method getId()Ljava/lang/String; in class Lml/docilealligator/infinityforreddit/utils/APIUtils; or its super classes (declaration of 'ml.docilealligator.infinityforreddit.utils.APIUtils' appears in /data/app/~~OVvOZLi1fmZrx2CrkXwbJw==/ml.docilealligator.infinityforreddit-2nyJc6JTT2M8gm8JlOgqiA==/base.apk)
	at ml.docilealligator.infinityforreddit.activities.LoginActivity.onCreate(Unknown Source:101)
	at android.app.Activity.performCreate(Activity.java:8767)
	at android.app.Activity.performCreate(Activity.java:8739)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1475)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4005)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4181)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8848)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)


`` END of stacktrace ``

**Comment by Honkertonken** [comment]
A restart and 7 reinstalls seems to have fixed the issue, no clue why.
