### ISSUE TITLE
crash when download

### ISSUE THREAD

**Issue by roastme** [Docile-Alligator/Infinity-For-Reddit#1725]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.3.0?

### Where did you get the app from

Other

### Android version

14, crdroid custom rom

### Device model

Xiaomi Redmi Note 13 NFC

### First occurred

about 5 days ago when i installed the rom

### Steps to reproduce

1. Go to a post with image and click download
2. Crash

### Example post, link, markdown...

https://www.reddit.com/r/comedyheaven/comments/1g8t8aa/computer_science/

### Expected behaviour

It download image without crashing

### Current behaviour

It crashed. I think that the problem is with the custom ROM but i would want to know how to fix it. Also it doesn't ask for media or files permission in settings and I can't grant it 

### Logs

```
`` Stacktrace ``

java.lang.IllegalArgumentException: Volume external_primary not found
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:154)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:589)
	at android.content.ContentResolver.insert(ContentResolver.java:2209)
	at android.content.ContentResolver.insert(ContentResolver.java:2171)
	at ml.docilealligator.infinityforreddit.services.DownloadMediaService.writeResponseBodyToDisk(DownloadMediaService.java:792)
	at ml.docilealligator.infinityforreddit.services.DownloadMediaService.downloadMedia(DownloadMediaService.java:639)
	at ml.docilealligator.infinityforreddit.services.DownloadMediaService.lambda$onStartJob$0$ml-docilealligator-infinityforreddit-services-DownloadMediaService(DownloadMediaService.java:460)
	at ml.docilealligator.infinityforreddit.services.DownloadMediaService$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


`` END of stacktrace ``

`` Thread info ``

Name: pool-5-thread-2
ID: 391
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 44
Thread time: 0 hr 0 min, 0 sec

`` END of thread info ``

`` Device info ``

Report ID: 7189621b-8d87-4c9e-887e-cc70f06a1ffb
Device ID: 7d1d3bc16ade9025
Application version: 179
Default launcher: com.android.launcher3
Timezone name: Irkutsk Standard Time
Timezone ID: Asia/Irkutsk
Version release: 14
Version incremental : eng.nobody.20241019.180117
Version SDK: 34
Board: bengal
Bootloader: unknown
Brand: Redmi
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: sapphiren
Display: AP2A.240905.003
Fingerprint: Redmi/sapphiren_global/sapphiren:14/AP2A.240905.003/eng.nobody.20241019.180117:user/release-keys
Hardware: qcom
Host: android-build
ID: AP2A.240905.003
Manufacturer: Xiaomi
Product: sapphiren_global
Build time: 1729353671000
Build time formatted: 20-10-2024 00:01:11
Type: user
Radio: MPSS.HA.1.1.c1-00097-DIVAR_GENSP_PACK-1,MPSS.HA.1.1.c1-00097-DIVAR_GENSP_PACK-1
Tags: release-keys
User: nobody
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_SEVERE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 92
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 8
Up time with sleep: 7 hr 22 min, 58 sec
Up time without sleep: 5 hr 16 min, 20 sec

`` END of Device info ``

`` Exit reasons ``


`` Exit reason #1 ``
Description: depends on provider com.android.providers.media.module/com.android.providers.media.MediaProvider in dying proc com.android.providers.media.module (adj -10000)
Importance: FOREGROUND
Reason: DEPENDENCY_DIED
Timestamp: 21-10-2024 02:17:03
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: ISOLATED NOT NEEDED isolated not needed
Importance: SERVICE
Reason: OTHER
Timestamp: 21-10-2024 00:02:54
`` END of exit reason #2 ``


`` END of exit reasons ``

`` Application info ``

App name: Infinity
Version code: 179
Version name: 7.3.0
Package name: ml.docilealligator.infinityforreddit
Short package name: infinityforreddit
Flavor: N/A
Signatures: UWMexcuMb9vRf/AuX0K4On8EgTo=
Is debuggable: No
First installed: 21-10-2024 00:01:39
Last updated: 21-10-2024 00:01:39
Requested permissions: android.permission.ACCESS_NETWORK_STATE, android.permission.INTERNET, android.permission.SET_WALLPAPER, android.permission.SET_WALLPAPER_HINTS, android.permission.FOREGROUND_SERVICE, android.permission.WAKE_LOCK, android.permission.POST_NOTIFICATIONS, android.permission.RUN_USER_INITIATED_JOBS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.RECEIVE_BOOT_COMPLETED, ml.docilealligator.infinityforreddit.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: mute_autoplaying_videos = true, wallpaper_id = 17, start_autoplay_visible_area_offset_portrait = 75, user_default_sort_type = NEW, video_autoplay = 0, link_handler = 0, legacy_autoplay_video_controller_ui = false, remember_muting_option_in_post_feed = false, language = en, mute_nsfw_video = true, notificaiton_interval = 1, user_default_sort_time = ALL, start_autoplay_visible_area_offset_landscape = 50, enable_search_history = true, default_playback_speed = 200, subreddit_default_sort_type = HOT, automatically_try_redgifs = true, amoled_dark = true, save_sort_type = true, use_bottom_toolbar_in_media_viewer = false, theme = 1, post_feed_max_resolution = 5000000, enable_notification = true, subreddit_default_sort_time = ALL, lazy_mode_interval = 2.5, mute_video = true, save_front_page_scrolled_position = true, pull_notification_time = 1729444653123, show_absolute_number_of_votes = true, main_page_back_button_action = 2, autoplay_nsfw_videos = false, hide_fab_in_post_feed = false, video_player_ignore_nav_bar = false, vote_buttons_on_the_right = false, hide_subreddit_description = false, loop_video = true, bottom_app_bar = false, respect_subreddit_recommended_comment_sort_type = false, easier_to_watch_in_full_screen = false, default_search_result_tab = 0, enable_material_you = false, video_player_automatic_landscape_orientation = true
Default prefs: mute_autoplaying_videos = true, wallpaper_id = 17, start_autoplay_visible_area_offset_portrait = 75, user_default_sort_type = NEW, video_autoplay = 0, link_handler = 0, legacy_autoplay_video_controller_ui = false, remember_muting_option_in_post_feed = false, language = en, mute_nsfw_video = true, notificaiton_interval = 1, user_default_sort_time = ALL, start_autoplay_visible_area_offset_landscape = 50, enable_search_history = true, default_playback_speed = 200, subreddit_default_sort_type = HOT, automatically_try_redgifs = true, amoled_dark = true, save_sort_type = true, use_bottom_toolbar_in_media_viewer = false, theme = 1, post_feed_max_resolution = 5000000, enable_notification = true, subreddit_default_sort_time = ALL, lazy_mode_interval = 2.5, mute_video = true, save_front_page_scrolled_position = true, pull_notification_time = 1729444653123, show_absolute_number_of_votes = true, main_page_back_button_action = 2, autoplay_nsfw_videos = false, hide_fab_in_post_feed = false, video_player_ignore_nav_bar = false, vote_buttons_on_the_right = false, hide_subreddit_description = false, loop_video = true, bottom_app_bar = false, respect_subreddit_recommended_comment_sort_type = fal
```

**Comment by Docile-Alligator** [comment]
Are you using LineageOS?

**Comment by roastme** [comment]
yes
