### ISSUE TITLE
Infinity crashes often

### ISSUE THREAD

**Issue by AlexJoaquimPereira** [Docile-Alligator/Infinity-For-Reddit#1740]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.4.0

### Where did you get the app from

Other

### Android version

12

### First occurred

About a week ago

### Steps to reproduce

1. Use the app on multiple accounts
2. After some time it will stop showing UI elements or even load content
3. Crash occurs (I have linked the crash report)

### Logs

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String z8.a.b()' on a null object reference
	at G8.t.a(SourceFile:1)
	at ml.docilealligator.infinityforreddit.activities.CommentActivity.l2(SourceFile:174)
	at ml.docilealligator.infinityforreddit.activities.CommentActivity.onOptionsItemSelected(SourceFile:60)
	at android.app.Activity.onMenuItemSelected(Activity.java:4418)
	at d.j.onMenuItemSelected(SourceFile:6)
	at s0.k.onMenuItemSelected(SourceFile:1)
	at i.c.onMenuItemSelected(SourceFile:1)
	at n.i.onMenuItemSelected(SourceFile:3)
	at i.E$b.onMenuItemClick(SourceFile:6)
	at androidx.appcompat.widget.Toolbar$a.onMenuItemClick(SourceFile:19)
	at androidx.appcompat.widget.ActionMenuView$d.a(SourceFile:7)
	at androidx.appcompat.view.menu.e.h(SourceFile:5)
	at androidx.appcompat.view.menu.g.k(SourceFile:15)
	at androidx.appcompat.view.menu.e.P(SourceFile:13)
	at androidx.appcompat.view.menu.e.O(SourceFile:2)
	at androidx.appcompat.widget.ActionMenuView.a(SourceFile:4)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(SourceFile:7)
	at android.view.View.performClick(View.java:7745)
	at android.view.View.performClickInternal(View.java:7722)
	at android.view.View.access$3700(View.java:854)
	at android.view.View$PerformClick.run(View.java:29111)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by Docile-Alligator** [comment]
Were you sending comments when this happened?
