### ISSUE TITLE
Frequent crashes on Redmi Note 4

### ISSUE THREAD

**Issue by SamarthH** [Docile-Alligator/Infinity-For-Reddit#216]
The error generated is pasted below.

android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at ml.docilealligator.infinityforreddit.Adapter.PostRecyclerViewAdapter.y()
	at androidx.recyclerview.widget.RecyclerView$g.g()
	at androidx.recyclerview.widget.RecyclerView$v.I()
	at d.t.d.j.i()
	at d.t.d.j.c()
	at d.t.d.j.d()
	at d.t.d.j.g()
	at d.t.d.j.run()
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
	at f.g.a.b.e0.o.e()
	at f.g.a.b.e0.o.a()
	at f.g.a.b.e0.o.b()
	at f.g.a.b.e0.o.h()
	at com.google.android.material.card.MaterialCardView.<init>()
	at com.google.android.material.card.MaterialCardView.<init>()
	... 22 more

**Comment by Docile-Alligator** [comment]
Thank you. What is your app version? What did you do before the crash?

**Comment by Docile-Alligator** [comment]
Would you like to install the latest beta by either join the beta program or from https://github.com/Docile-Alligator/Infinity-For-Reddit/releases ? This will be easier for me to debug.

**Comment by Docile-Alligator** [comment]
What is your Android version?
