### ISSUE TITLE
Crash when downloading an image with Mime type image/*

### ISSUE THREAD

**Issue by PeteS4** [Docile-Alligator/Infinity-For-Reddit#309]
Trying to download certain images leads to a crash, for example:
https://www.reddit.com/r/BirdsForScale/comments/mje2tp/arrows_by_alexey_egorov/
```
04-04 09:30:37.453 E/AndroidRuntime(9935): FATAL EXCEPTION: ServiceStartArguments
04-04 09:30:37.453 E/AndroidRuntime(9935): Process: ml.docilealligator.infinityforreddit, PID: 9935
04-04 09:30:37.453 E/AndroidRuntime(9935): java.lang.IllegalArgumentException: Unsupported MIME type image/*
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at android.content.ContentResolver.insert(ContentResolver.java:2149)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at android.content.ContentResolver.insert(ContentResolver.java:2111)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at ml.docilealligator.infinityforreddit.services.DownloadMediaService$ServiceHandler.writeResponseBodyToDisk(DownloadMediaService.java:267)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at ml.docilealligator.infinityforreddit.services.DownloadMediaService$ServiceHandler.handleMessage(DownloadMediaService.java:221)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at android.os.Looper.loop(Looper.java:223)
04-04 09:30:37.453 E/AndroidRuntime(9935): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by Docile-Alligator** [comment]
Thank you for reporting it!

**Comment by Docile-Alligator** [comment]
Fixed.
