### ISSUE TITLE
[BUG][BETA] Crash when in gallery

### ISSUE THREAD

**Issue by PinkDev1** [Docile-Alligator/Infinity-For-Reddit#324]
```java
This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: ml.docilealligator.infinityforreddit
PID: 7097
Flags: 0x28c8be44
Package: ml.docilealligator.infinityforreddit v62 (4.3.0-beta2)
Foreground: Yes
Build: motorola/pokerp_64/pokerp:9/PTBS29.401-58-2/58-2:user/release-keys

java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2205)
	at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2584)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3083)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3083)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3083)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3083)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3083)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3083)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3083)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:474)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:432)
	at android.view.View.dispatchPointerEvent(View.java:12799)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5317)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5111)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4624)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4677)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4643)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4783)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4651)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4840)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4624)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4677)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4643)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4651)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4624)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7397)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7349)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7300)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7554)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7521)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7584)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1009)
	at android.view.Choreographer.doCallbacks(Choreographer.java:779)
	at android.view.Choreographer.doFrame(Choreographer.java:702)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:235)
	at android.app.ActivityThread.main(ActivityThread.java:6760)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

```

I was moving throug the images of this post when the crash happened: https://www.reddit.com/r/MoeMorphism/comments/mw9w4x/quantum_festival_what_is_nuclear_waste/

**Comment by Docile-Alligator** [comment]
Hi, I think this rarely happens. Just don't swipe right or left too quickly.
