### ISSUE TITLE
App crashes when trying to view a user profile

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#520]
Version: 5.1.0-beta2
Android: 10 (lineageos without google play services)

**Comment by Poomex** [comment]
Can confirm, here's the log:

`FATAL EXCEPTION: main
Process: ml.docilealligator.infinityforreddit, PID: 5104
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at ml.docilealligator.infinityforreddit.activities.ViewUserDetailActivity.onCreateOptionsMenu(ViewUserDetailActivity.java:1025)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4092)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:722)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)`

**Comment by Docile-Alligator** [comment]
Fixed.

**Comment by Poomex** [comment]
Thanks for your work, great app!
