### ISSUE TITLE
[Bug] BitmapRegionDecoder fails to decode some WebP images on older Android versions (5.1.1 SDK 22)

### ISSUE THREAD

**Issue by scria1000** [Docile-Alligator/Infinity-For-Reddit#558]
On Android 5.1.1

https://user-images.githubusercontent.com/91804886/143874361-34f96196-3394-4339-ba9b-43e6f9bbc40d.mp4

**[Here is the post link for a repro.](https://www.reddit.com/r/dataisbeautiful/comments/qxsb78/oc_drug_related_deaths_in_the_us_aggregate_and_by/)**

``````
java.lang.Class<androidx.exifinterface.media.ExifInterface$1>
    Rejecting re-init on previously-failed class java.lang.Class<androidx.exifinterface.media.ExifInterface$1>
D/skia: --- decoder->buildTileIndex returned false
E/SubsamplingScaleImageView: Failed to initialise bitmap decoder
    java.io.IOException: Image failed to decode using JPEG decoder
        at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
        at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
D/skia: --- decoder->buildTileIndex returned false
``````

I'm not sure if it is the fault of the underlying implementation of `BitmapRegionDecoder` or any of the image libraries (`BigImageViewer`, `SubsamplingScaleImageView` which is used by `BigImageViewer` ) used inside the gallery fragment. I have tested the images with the latest Glide example app for `BigImageViewer`, and got the same exception. What I don't understand is, why is it running a JPEG decoder on what is actually a WebP file? Also no issues opening these images in the Gallery.

I already implemented a fallback mechanism that can load the original `i.redd.it` media url (https://i.redd.it/6y746muezm081.jpg) when necessary. A PR will soon follow.
Also worth mentioning; the image downloading feature does not actually save the original `i.redd.it` media image, at least, not for albums. Instead, it saves the converted WebP image and then inflates its original size by converting back to JPEG again.

**Comment by scria1000** [comment]
It seems that prior to API 24, BitmapRegionDecoder does not check the file header of the image, but relies on file extension?

[This causes an exception](https://preview.redd.it/6y746muezm081.jpg?width=870&format=pjpg&auto=webp&s=1b37b7743fa70b6e617f92154fcbcdfab4e90eff)
[This does not](https://i.ibb.co/ZMwC5vC/6y746muezm081.webp)

They are byte identical.

But the file extension is lost during prefetching?
