### ISSUE TITLE
Crash upon attempt to download media

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#58]
when viewing an image, animation or video, clicking the icon for download crashes the app at all times

**Comment by Docile-Alligator** [comment]
That's really bad. What Android version are you using?

**Comment by Wilker-a** [comment]
v5.1.1 Marshmallow

v2.2.3 of the app as of now

**Comment by OHermesJunior** [comment]
Does this still happens? I can't replicate with Android 5.1.1 and the last version of the app.

**Comment by Wilker-a** [comment]
still an issue :(

###### unfortunately i don't know any means to get a log of the crash without root, as i don't have an accessible desktop computer, nor do i know what to do to root without, as there are no known ways to get root tools for my phone model without a pc. :\

**Comment by BlackRabbit22** [comment]
It's happening to me as well and I'm Android 9....

**Comment by Wilker-a** [comment]
the crash persists (v3.2.0) :\

###### i don't use Play Services btw

**Comment by Wilker-a** [comment]
i have finally managed to enable a log reader, and the following image is the Exception information
![crash-inf](https://user-images.githubusercontent.com/10854855/84942329-2a72aa80-b0d2-11ea-9178-cf666b4853c8.png)

transcript: 
```ActivityThread(11433): Failed to find provider info for downloads
06-17 16:24:30.671 E/AndroidRuntime(11433): FATAL EXCEPTION: main
06-17 16:24:30.671 E/AndroidRuntime(11433): Process: ml.docilealligator.infinityforreddit, PID: 11433
06-17 16:24:30.671 E/AndroidRuntime(11433): java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.content.ContentResolver.insert(ContentResolver.java:1256)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.app.DownloadManager.enqueue(DownloadManager.java:1336)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at ml.docilealligator.infinityforreddit.Activity.ViewImageActivity.download(ViewImageActivity.java:305)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at ml.docilealligator.infinityforreddit.Activity.ViewImageActivity.onOptionsItemSelected(ViewImageActivity.java:205)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.app.Activity.onMenuItemSelected(Activity.java:3201)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1030)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.view.View.performClick(View.java:5246)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.widget.TextView.performClick(TextView.java:10602)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.view.View$PerformClick.run(View.java:21256)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.os.Handler.handleCallback(Handler.java:739)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.os.Looper.loop(Looper.java:145)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at android.app.ActivityThread.main(ActivityThread.java:6917)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at java.lang.reflect.Method.invoke(Native Method)
06-17 16:24:30.671 E/AndroidRuntime(11433): 	at java.lang.reflect.Method.invoke(Method.java:372)```

from what i can tell, it is perhaps trying to gather information for a download to a folder which doesn't exist. if this is correct, a proper handling would be to just notify the user and create such folder. another good thing to do is to include an option for choosing the directory for saving these.

**Comment by Docile-Alligator** [comment]
Thanks for the crash log. Did you disable Download Manager in your Android system? If so, please enable it.

**Comment by Wilker-a** [comment]
yes, i had it disabled.. enabling it seems to have solved this issue, although i don't really like having Samsung stuff enabled in this phone...

thank you \^_\^

**Comment by Wilker-a** [comment]
it's been a month since the problem of the issue has been fixed, i guess. should we close it? i will be closing it..

**Comment by Wilker-a** [comment]
unless there is an Exception handling to be done \^\^'
